keycloak:
  # Once the Helm chart is installed, you need to specify the route that was
  # automatically created by OpenShift for RH-SSO. To do so, you must upgrade
  # the Helm chart and replace the value of keycloak.url in the chart's values
  # with the URL of the keycloak Route resource with the /auth endpoint.
  url: fix-me-after-installation
eap74:
  build:
    uri: https://github.com/deewhyweb/eap-coolstore-monolith.git
    ref: ocp
    s2i:
      featurePacks:
        - 'org.jboss.eap:eap-datasources-galleon-pack:7.4.0.GA-redhat-00003'
      galleonLayers:
        - cloud-server
        - postgresql-datasource
        - ejb
        - web-clustering
    env:
      - name: POSTGRESQL_DRIVER_VERSION
        value: 42.6.0
  deploy:
    enabled: false