database:
  name: sampledb
  user: "my-user"
  password: "my-password"
eap74:
  build:
    uri: https://github.com/jboss-eap-up-and-running/eap7-with-postgres
    s2i:
      featurePacks:
        - org.jboss.eap:eap-datasources-galleon-pack:7.4.0.GA-redhat-00003
      galleonLayers: 
        - cloud-server
        - postgresql-datasource
    env:
      - name: POSTGRESQL_DRIVER_VERSION
        value: '42.2.19'
  deploy:
    env:
      # Env vars to connect to PostgreSQL DB
      - name: POSTGRESQL_DATABASE
        valueFrom:
          secretKeyRef:
            key: database-name
            name: postgresql
      - name: POSTGRESQL_USER
        valueFrom:
          secretKeyRef:
            key: database-user
            name: postgresql
      - name: POSTGRESQL_PASSWORD
        valueFrom:
          secretKeyRef:
            key: database-password
            name: postgresql
      - name: POSTGRESQL_DATASOURCE
        value: qs-ds
      - name: POSTGRESQL_SERVICE_HOST
        value: postgresql