apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: eap74-amq7
spec:
  acceptors:
    - name: my-acceptor
      port: 5672
      protocols: 'amqp,openwire'
  deploymentPlan:
    image: placeholder
    jolokiaAgentEnabled: false
    journalType: nio
    managementRBACEnabled: true
    messageMigration: false
    persistenceEnabled: false
    requireLogin: false
    size: 2
  console:
    expose: true
---
apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemisAddress
metadata:
  name: artemis-address-topic
spec:
  addressName: topic.orders
  queueName: topic/orders
  routingType: multicast