---
kind: Keycloak
apiVersion: keycloak.org/v1alpha1
metadata:
  name: eap-sso
  labels:
    app: sso
spec:
  instances: 1
  externalAccess:
    enabled: true
---

kind: KeycloakRealm
apiVersion: keycloak.org/v1alpha1
metadata:
  name: eap-realm
  labels:
    app: sso
spec:
  realm:
    id: eap
    realm: eap
    enabled: true
    displayName: Basic Realm
  instanceSelector:
    matchLabels:
      app: sso

---
kind: KeycloakClient
apiVersion: keycloak.org/v1alpha1
metadata:
  name: eap-app
  labels:
    app: sso
spec:
  realmSelector:
    matchLabels:
      app: sso
  client:
    redirectUris:
      - '*'
    webOrigins:
      - '*'
    clientId: eap-app
    secret: client-secret
    clientAuthenticatorType: client-secret
    enabled: true
    publicClient: true
    standardFlowEnabled: true

---
apiVersion: keycloak.org/v1alpha1
kind: KeycloakUser
metadata:
  name: example-realm-user
  labels:
    app: sso
spec:
  realmSelector:
    matchLabels:
      app: sso
  user:
    credentials:
      - type: password
        value: pass
    username: user1
    firstName: John
    lastName: Doe
    email: user@example.com
    enabled: true
    emailVerified: false